### ISSUE TITLE
[PE-D][Tester C] What is `remark`?

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103-W16-4/tp#104]
There is an option to sort by remark, which doesnt do anything.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: arkarsg/ped#3

**Comment by ajjajjajjajj** [comment]
Sorting by remark actually does something, as long as there are existing remarks. Invalid bug report, however:

@wpx12011 please consider adding in default remarks for sample contacts under `SampleDataUtil.java`.

**Comment by ajjajjajjajj** [comment]
@evanpy to remove sorting by remarks from sort.
