### ISSUE TITLE
[PE-D][Tester D] Command summary does not reflect all the commands. 

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103-W16-4/tp#106]
![image.png](https://raw.githubusercontent.com/mayuanxin1234/ped/main/files/cc9eccbd-53ab-47f9-bc5e-494e38276f8f.png)

There are 20+ commands but only 12 commands in summary. Also, italic-optional should not be shown. 

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: mayuanxin1234/ped#8

**Comment by ajjajjajjajj** [comment]
@everyone to update command summary with all commands that you've added.
