### ISSUE TITLE
[PE-D][Tester D] Help shows old ab3 userguide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103-W16-4/tp#107]
![image.png](https://raw.githubusercontent.com/mayuanxin1234/ped/main/files/b9f7789a-44b8-4824-813b-ae47bf38a931.png)

Wrong link for help. 

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: mayuanxin1234/ped#9

**Comment by ajjajjajjajj** [comment]
@ajjajjajjajj to edit the help link
