### ISSUE TITLE
[PE-D][Tester D] Findall clarification

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103-W16-4/tp#110]
Might be useful to highlight that findall does not work for leads and tags, they have their own separate commands in the userguide. 

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: mayuanxin1234/ped#11

**Comment by ajjajjajjajj** [comment]
@WesleyBLDC consider updating the documentation to reflect this.
