### ISSUE TITLE
[PE-D][Tester A] Empty table of contents in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103-W16-4/tp#111]
Table of content in UG is empty.

![image.png](https://raw.githubusercontent.com/ChinJunAn/ped/main/files/67a852c4-3b4d-4043-84e4-8d6d3359b490.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: ChinJunAn/ped#2

**Comment by ajjajjajjajj** [comment]
Duplicate issue. Refer to #102.
