### ISSUE TITLE
[PE-D][Tester C] Command format of addtxn

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103-W16-4/tp#120]
addtxn does not support
`addtxn td/Sample Transaction tv/100 ts/open to/John Doe`
as given in the example

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: arkarsg/ped#5

**Comment by ajjajjajjajj** [comment]
Duplicate issue – refer to #95. @wpx12011 to take note.
