### ISSUE TITLE
[PE-D][Tester D] edittxn allows me to edit to duplicate transactions 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103-W16-4/tp#135]
![image.png](https://raw.githubusercontent.com/mayuanxin1234/ped/main/files/618ec404-0c37-4ce4-8e30-4fe46d714b8f.png)

If i edittxn 1 td/sample, it does not allow me to edit as it will create duplicate transactions. However, if I use td/sample tv/100, 2 transactions of sample would be created which would be duplicate and is wrong. Attached video

<i><video controls><source src="https://raw.githubusercontent.com/mayuanxin1234/ped/main/files/4f05f253-a504-433a-978e-747fcdb3c24f.mp4" type="video/mp4">Your browser does not support the video tag.</video><br>video:https://raw.githubusercontent.com/mayuanxin1234/ped/main/files/4f05f253-a504-433a-978e-747fcdb3c24f.mp4</i>

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: mayuanxin1234/ped#16

**Comment by ajjajjajjajj** [comment]
@wpx12011 to consider if you want the current definition of duplicate transactions to be a feature. You might want to change the definition of `isSameTransaction()` to just match the same description, to prevent confusion by the user such as this case.

**Comment by wpx12011** [comment]
The current definition of duplicate transaction is: 
1. Same description
2. Same Owner
3. Same value
4. (Status not included)

So currently we allow a transaction to have same description, same owner, same status but different value, which is the case reported by this tester.

Action: will update a more detailed definition of duplicate transactions in UG.
