### ISSUE TITLE
[PE-D][Tester A] Wrong example in addtxn command

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103-W16-4/tp#136]
Example says ts/open is possible. But app says it has to be spelled "Open"

![image.png](https://raw.githubusercontent.com/ChinJunAn/ped/main/files/595c7226-fe64-43d6-a2c7-86b82487bfc6.png)

![image.png](https://raw.githubusercontent.com/ChinJunAn/ped/main/files/e96a01cb-7b70-4ba4-9257-4ccd3e9cf04a.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: ChinJunAn/ped#10

**Comment by ajjajjajjajj** [comment]
Duplicate issue with #95.
