### ISSUE TITLE
Command example for `add` is a duplicate of default data

### ISSUE THREAD

**Issue by ajjajjajjajj** [AY2223S2-CS2103-W16-4/tp#155]
The first command example for the `add` command is a duplicate person based on the sample data for a new user of SalesPunch.
Consider changing the person's details for this command example so that it works for a new user.

<img width="790" alt="Screenshot 2023-04-05 at 4 31 21 PM" src="https://user-images.githubusercontent.com/86147552/230026348-71bbaec8-909a-464d-afd7-92a39b2b08dd.png">
<img width="1251" alt="Screenshot 2023-04-05 at 4 32 47 PM" src="https://user-images.githubusercontent.com/86147552/230026636-1b4581b8-4e5a-4b0d-b6b0-58c25f5e885a.png">

**Comment by evanpy** [comment]
Fixed in PR [#178](https://github.com/AY2223S2-CS2103-W16-4/tp/pull/178)
