### ISSUE TITLE
Edit command does not give helpful error message for 0 or negative numbers

### ISSUE THREAD

**Issue by benedict733** [AY2223S2-CS2103-W16-4/tp#157]
The error message can highlight the index instead of just showing full command format

![image](https://user-images.githubusercontent.com/86705708/230027572-4dd35e00-a823-43a9-8312-be5ecb327864.png)

**Comment by evanpy** [comment]
A general command usage message would suffice in my opinion since this is also the origin response for AB3. Although, I do agree with you that segmenting the messaging could improve user experience.
