### ISSUE TITLE
Edit command is unable to accept bigger numbers

### ISSUE THREAD

**Issue by benedict733** [AY2223S2-CS2103-W16-4/tp#159]
Example of number at integer limit 
![image](https://user-images.githubusercontent.com/86705708/230028655-f6076200-f20c-49bb-85b2-e70db4828129.png)

Example of number at bigger than integer limit, wrong error message
![image](https://user-images.githubusercontent.com/86705708/230028733-6c251400-d63f-4fb9-9a97-c01a972ff75c.png)

**Comment by evanpy** [comment]
Think you are right about mentioning this in the UG.
