### ISSUE TITLE
UG remove all remark

### ISSUE THREAD

**Issue by WesleyBLDC** [AY2223S2-CS2103-W16-4/tp#160]
![image](https://user-images.githubusercontent.com/28299779/230028861-f038bfdc-246d-4618-8282-4bc025485cb5.png)

Still inside the summary command table

@evanpy

**Comment by evanpy** [comment]
I've removed it in my merged PR already but not sure why it reappeared. Could you help to remove it for me? Thanks a lot.

**Comment by evanpy** [comment]
Fixed in PR [#178](https://github.com/AY2223S2-CS2103-W16-4/tp/pull/178)
