### ISSUE TITLE
Lead status updates when not supposed to 

### ISSUE THREAD

**Issue by benedict733** [AY2223S2-CS2103-W16-4/tp#162]
Contact list before change of name
![image](https://user-images.githubusercontent.com/86705708/230029055-67d42a6a-0910-4c60-b614-e697ac6fd1ed.png)

After edit 7 n/Amy Bee, lead status is updated to 0 seconds ago
Same thing happens when I change location
![image](https://user-images.githubusercontent.com/86705708/230029359-5cfee9e0-e3d3-49d7-a713-de1ea2bea25e.png)

**Comment by ajjajjajjajj** [comment]
fixed with PR #180
