### ISSUE TITLE
Status unable to accept lowercase commands

### ISSUE THREAD

**Issue by benedict733** [AY2223S2-CS2103-W16-4/tp#171]
unable to do status 1 s/u or status 1 s/uncontacted

![image](https://user-images.githubusercontent.com/86705708/230031954-69cad1ba-773c-4761-88d8-5b543a06cbf5.png)
![image](https://user-images.githubusercontent.com/86705708/230032063-810ad5f4-1c1f-4005-996e-2d9cf02fe4c3.png)

**Comment by ajjajjajjajj** [comment]
Is a feature flaw; and also the UG already specifies the case-sensitive format of statuses
