### ISSUE TITLE
when editing 

### ISSUE THREAD

**Issue by benedict733** [AY2223S2-CS2103-W16-4/tp#172]
find amy bee
after editing a contact
goes back to entire contact list

![image](https://user-images.githubusercontent.com/86705708/230033249-1f7265bb-edbd-4551-bb5c-b71ecd4abd1c.png)
![image](https://user-images.githubusercontent.com/86705708/230033340-3910d739-67eb-4597-8dbf-32b2445b66b0.png)

**Comment by evanpy** [comment]
Hmm, good catch but I suppose that is the default process since edit command would naturally overwrite the find command. Good consideration, though, for user experience.
