### ISSUE TITLE
edittxn feature: deleted contact with lingering transaction

### ISSUE THREAD

**Issue by evanpy** [AY2223S2-CS2103-W16-4/tp#183]
Just to confirm this is intended feature: delete contact does not delete transaction tied to him?

edittxn can not edit transaction anymore after contact has been deleted, refer to image below:

![image](https://user-images.githubusercontent.com/38004268/230669258-94980453-309a-4a78-88f4-c6e9ab0a40ea.png)

Also, `This transaction record has to be assigned to a existing person in the sales book` has some errors:
1. `a existing` to `an existing`
2. `sales book` to `contact list`

**Comment by ajjajjajjajj** [comment]
If we're not intending to implement this, let's instead add this to the 'Possible Enhancements' section of the DG? Sounds like a fitting feature to add.
