### ISSUE TITLE
[PE-D][Tester D] Prefix summary

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103-W16-4/tp#96]
Some prefixes are hard to know the meaning and it might be useful to have a prefix summary at end of user guide. 

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: mayuanxin1234/ped#2

**Comment by ajjajjajjajj** [comment]
Please consider shortening prefixes to one letter. Transactions and tasklist do not have to have two-letter prefixes, as prefixes don't have to be globally unique, only unique within the commands they're used in.

**Comment by WesleyBLDC** [comment]
Improve the summary guide at the bottom that mentions all the commands and shortforms
